# Generated by Django 2.2.24 on 2021-11-16 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgAnnotationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation_id', models.CharField(max_length=50, unique=True)),
                ('role', models.TextField(choices=[('staff', 'staff'), ('student', 'student')])),
                ('body', models.TextField(blank=True, default='')),
                ('course_key', opaque_keys.edx.django.models.CourseKeyField(default=None, max_length=255)),
                ('usage_key', opaque_keys.edx.django.models.UsageKeyField(default=None, max_length=255)),
                ('target', models.CharField(default='', max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('annotation_id', 'user', 'course_key', 'usage_key')},
                'index_together': {('annotation_id', 'user', 'course_key', 'usage_key')},
            },
        ),
    ]
