# Generated by Django 2.2.24 on 2022-01-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_annotation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgannotationmodel',
            name='target',
            field=models.TextField(blank=True, default=''),
        ),
    ]
