# Generated by Django 2.2.24 on 2025-04-03 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('img_annotation', '0002_auto_20220118_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverlayModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(choices=[('highlighted_overlay', 'rectangle_overlay'), ('fixed_size_overlay', 'arrow_overlay')])),
                ('course_key', opaque_keys.edx.django.models.CourseKeyField(default=None, max_length=255)),
                ('usage_key', opaque_keys.edx.django.models.UsageKeyField(default=None, max_length=255)),
                ('height', models.DecimalField(blank=True, decimal_places=30, max_digits=32, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=30, max_digits=32, null=True)),
                ('position_x', models.DecimalField(decimal_places=30, max_digits=32)),
                ('position_y', models.DecimalField(decimal_places=30, max_digits=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'index_together': {('course_key', 'usage_key')},
            },
        ),
    ]
